### ISSUE TITLE
Publish 1.1.0 to Docker Hub

### ISSUE THREAD

**Issue by atkinchris** [ara-framework/nova-proxy#12]
[Release 1.1.0](https://github.com/ara-framework/nova-proxy/releases/tag/1.1.0) is published to GitHub, introducing custom ports, but is not published to Docker Hub. The latest published image is [1.0.5](https://hub.docker.com/layers/araframework/nova-proxy/1.0.5/images/sha256-d992660a373f9202ad661b499d489266dab09567ee39d34c8041be0be22847c5?context=explore).

Please can the latest image be published?

**Comment by marconi1992** [comment]
Hi @atkinchris , sorry for the late reply.  I already published the new version, thanks for the heads-up! https://hub.docker.com/layers/araframework/nova-proxy/1.1.0/images/sha256-9cb6565f34ffb053304162448ca071aad76a40e5dba2bbc3a468695107e8977a?context=repo

However, we'll consider deprecating de docker image in the upcoming versions in favor of the Ara CLI.

**Comment by atkinchris** [comment]
Thanks!
